import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className="mt-6 text-center text-xl font-medium tracking-tight text-gray-900">
          <a
            href="/login"
            className="bg-gray-700 text-white px-3 py-2 rounded-md hover:bg-white hover:text-gray-900"
          >
            Sign in
          </a>{" "}
          to your account to see details
        </h2>
        <Image src="/vercel.svg" alt="Vercel Logo" width={300} height={300} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Next.js
        </a>
      </footer>
    </div>
  );
};

export default Home;
